pipeline {
    agent any

    tools {
        jdk 'jdk11'
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'git@github.com:KingMicky/youtubepy.git'
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Sonarqube Analysis') {
            steps {
                    sh '''${SCANNER_HOME}/bin/sonar-scanner -Dsonar.url=http://3.89.30.254:9000/ -Dsonar.login=squ_2c77a02087efaf61e0859fc562f4d858b6612106 -Dsonar.projectname=youtubepy \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=youtubepy \ '''
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy'
            }
        }
    }
}