pipeline {
    agent any

    tools {
        jdk 'jdk11'
        maven 'maven3'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main',changelog:false, poll: false, url: https://github.com/KingMicky/all-together/tree/main/2/devops-automation-mainhttps://github.com/KingMicky/all-together/tree/main/2/devops-automation-main.git
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Sonarqube Analysis') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}